const worldThemes = [
    { en: { title: "WW2: The Last Bunker", desc: "Defend your post in the French countryside." }, fr: { title: "2GM : Le Dernier Bunker", desc: "Défendez votre poste dans la campagne française." } },
    { en: { title: "Cyber-Samurai Tokyo", desc: "Honor and steel in a neon-drenched future." }, fr: { title: "Cyber-Samouraï Tokyo", desc: "Honneur et acier dans un futur néon." } },
    { en: { title: "Xeno Hive Breach", desc: "Survive the infestation in deep space." }, fr: { title: "Invasion Xéno", desc: "Survivez à l'infestation dans l'espace lointain." } },
    { en: { title: "Zombie London", desc: "Escaping the undead in the fog." }, fr: { title: "Londres Zombie", desc: "Échapper aux morts-vivants dans le brouillard." } },
    { en: { title: "Mars Colonist", desc: "Build a life on the red planet." }, fr: { title: "Colon de Mars", desc: "Construisez une vie sur la planète rouge." } },
    // ... (Generating 50 themes)
    { en: { title: "Victorian Steampunk", desc: "Inventions and smog." }, fr: { title: "Steampunk Victorien", desc: "Inventions et smog." } },
    { en: { title: "Post-Apocalyptic Desert", desc: "Water is life." }, fr: { title: "Désert Post-Apocalyptique", desc: "L'eau est la vie." } },
    { en: { title: "Medieval High Fantasy", desc: "Magic and dragons." }, fr: { title: "Fantasy Médiévale", desc: "Magie et dragons." } },
    { en: { title: "Lovecraftian Harbor", desc: "Ancient secrets emerge." }, fr: { title: "Port Lovecraftien", desc: "Des secrets ancestraux émergent." } },
    { en: { title: "Galactic Trade Empire", desc: "Space merchant life." }, fr: { title: "Empire Commercial Galactique", desc: "Vie de marchand de l'espace." } },
    { en: { title: "Dystopian Megacity", desc: "Survive the corporate grind." }, fr: { title: "Mégapole Dystopique", desc: "Survivez à la machine corporative." } },
    { en: { title: "Wild West Supernatural", desc: "Cowboys meet spirits." }, fr: { title: "Far West Surnaturel", desc: "Cowboys rencontrent les esprits." } },
    { en: { title: "Atlantis Reborn", desc: "Explore the sunken city." }, fr: { title: "Atlantide Renaissante", desc: "Explorez la cité engloutie." } },
    { en: { title: "Roman Legion Frontier", desc: "Hold the line." }, fr: { title: "Frontière Légion Romaine", desc: "Tenez la ligne." } },
    { en: { title: "Cyberpunk Hacker", desc: "Infiltrate the mainframe." }, fr: { title: "Hacker Cyberpunk", desc: "Infiltrez le système central." } },
    { en: { title: "Arctic Survival", desc: "The cold is lethal." }, fr: { title: "Survie Arctique", desc: "Le froid est mortel." } },
    { en: { title: "Jungle Expedition", desc: "Uncover lost ruins." }, fr: { title: "Expédition dans la Jungle", desc: "Découvrez des ruines perdues." } },
    { en: { title: "Noir Detective 1940s", desc: "Solve the case." }, fr: { title: "Détective Noir 1940", desc: "Résolvez l'enquête." } },
    { en: { title: "High-Tech Pirates", desc: "Space treasure awaits." }, fr: { title: "Pirates High-Tech", desc: "Le trésor spatial attend." } },
    { en: { title: "Alchemist Laboratory", desc: "Transmute your destiny." }, fr: { title: "Laboratoire d'Alchimiste", desc: "Transmutez votre destin." } },
    { en: { title: "Dino Island Escape", desc: "Don't get eaten." }, fr: { title: "Évasion de l'Île aux Dinos", desc: "Ne vous faites pas manger." } },
    { en: { title: "Time Travel Paradox", desc: "Fix the timeline." }, fr: { title: "Paradoxe Temporel", desc: "Réparez la chronologie." } },
    { en: { title: "Space Horror Station", desc: "No one hears you." }, fr: { title: "Station d'Horreur Spatiale", desc: "Personne ne vous entend." } },
    { en: { title: "Samurai Clan Wars", desc: "Clash of swords." }, fr: { title: "Guerres de Clans Samouraïs", desc: "Choc des épées." } },
    { en: { title: "Wizard School", desc: "Learn the arts." }, fr: { title: "École de Sorciers", desc: "Apprenez les arts." } },
    { en: { title: "Robot Rebellion", desc: "The machines rise." }, fr: { title: "Rébellion des Robots", desc: "Les machines se soulèvent." } },
    { en: { title: "Haunted Mansion", desc: "Escape the spirits." }, fr: { title: "Manoir Hanté", desc: "Échappez aux esprits." } },
    { en: { title: "Deep Sea Mining", desc: "Pressure is absolute." }, fr: { title: "Exploitation Minière Sous-Marine", desc: "La pression est absolue." } },
    { en: { title: "Post-War Reconstruction", desc: "Build hope." }, fr: { title: "Reconstruction Après-Guerre", desc: "Construisez l'espoir." } },
    { en: { title: "Viking Raid", desc: "For Valhalla." }, fr: { title: "Raid Viking", desc: "Pour le Valhalla." } },
    { en: { title: "Gladiator Arena", desc: "Fight to win." }, fr: { title: "Arène de Gladiateurs", desc: "Combattez pour gagner." } },
    { en: { title: "Stealth Assassin", desc: "The shadows guide you." }, fr: { title: "Assassin de l'Ombre", desc: "Les ombres vous guident." } },
    { en: { title: "Fairy Tale Forest", desc: "Not as sweet as it seems." }, fr: { title: "Forêt de Contes de Fées", desc: "Pas aussi doux qu'il y paraît." } },
    { en: { title: "Cyber-Renegade", desc: "Defy the system." }, fr: { title: "Renégat Cyber", desc: "Défiez le système." } },
    { en: { title: "Underground Resistance", desc: "Fight for freedom." }, fr: { title: "Résistance Souterraine", desc: "Battez-vous pour la liberté." } },
    { en: { title: "Space Nomad", desc: "Travel the star lanes." }, fr: { title: "Nomade de l'Espace", desc: "Voyagez dans les routes stellaires." } },
    { en: { title: "Mythological Greek", desc: "Gods intervene." }, fr: { title: "Mythologie Grecque", desc: "Les dieux interviennent." } },
    { en: { title: "Desert Nomads", desc: "Survive the sandstorms." }, fr: { title: "Nomades du Désert", desc: "Survivez aux tempêtes de sable." } },
    { en: { title: "Spy Agency", desc: "Protect the state." }, fr: { title: "Agence d'Espionnage", desc: "Protégez l'État." } },
    { en: { title: "Monster Hunter", desc: "Track the beast." }, fr: { title: "Chasseur de Monstres", desc: "Traquez la bête." } },
    { en: { title: "Utopian Society", desc: "Or is it?" }, fr: { title: "Société Utopique", desc: "Ou l'est-ce ?" } },
    { en: { title: "Nuclear Wasteland", desc: "Search for clean water." }, fr: { title: "Terres Désolées Nucléaires", desc: "Cherchez de l'eau propre." } },
    { en: { title: "Undersea Kingdom", desc: "Rule the tides." }, fr: { title: "Royaume Sous-Marin", desc: "Dirigez les marées." } },
    { en: { title: "Witch Hunter", desc: "Purge the darkness." }, fr: { title: "Chasseur de Sorcières", desc: "Purgez les ténèbres." } },
    { en: { title: "Corporate Spy", desc: "Steal the data." }, fr: { title: "Espion Corporatif", desc: "Volez les données." } },
    { en: { title: "Solarpunk Paradise", desc: "Nature and tech coexist." }, fr: { title: "Paradis Solarpunk", desc: "Nature et technologie coexistent." } },
    { en: { title: "Detective Agency", desc: "Solve the city's crimes." }, fr: { title: "Agence de Détective", desc: "Résolvez les crimes de la ville." } },
    { en: { title: "Space Mining Colony", desc: "Life on the rock." }, fr: { title: "Colonie Minière Spatiale", desc: "La vie sur le caillou." } },
    { en: { title: "Fantasy Merchant", desc: "Sell anything to anyone." }, fr: { title: "Marchand de Fantasy", desc: "Vendez tout à n'importe qui." } }
];
